### ISSUE TITLE
Question about RPM package of libnf

### ISSUE THREAD

**Issue by cejkato2** [VUTBR/nf-tools#3]
Could you please provide some script / command that can be used for creation of RPM package of libnf? (I can see that spec file already exists)

Alternatively, is there any public repository that contains a stable version of libnf RPM?
Thank you very much.

**Comment by cejkato2** [comment]
Solved by #4.
Maybe, it should be added into README...
The solution is based on `rpmbuild` utility.
Build can be started by `make rpm`.

Additionally, `rpmbuild` can be checked by configure.

**Comment by tpoder1** [comment]
Thanks for submitting the patch. It looks very good. I merged it into master branch. I'll make note into README, ChangeLog and the specfile's changelog. RPMs are not available in any repository so far. I'd prefer to distribute RPMs via some standard repository like rpmforge or epel instead of creating a new libnf specific repository.
